

var height = 6; //number of guesses
var width = 6; //length of the word

var row = 0; //current guess (attempt #)
var col = 0; //current letter for that attempt

let score = 0;

var gameOver = false;
// var word = "SQUID";
var wordList = [
    'adhabu', 
    'afyuni', 
    'agulia', 
    'aidini', 
    'akania', 
    'akhiri', 
    'akrabu', 
    'adhimu', 
    'afandi', 
    'adisha',
    'ajwari', 
    'achana', 
    'adhana', 
    'afueni',
    'agizia',
    'aibika', 
    'akhera', 
    'albamu', 
    'anguka', 
    'anjari', 
    'askari', 
    'askofu', 
    'asmini', 
    'abiria', 
    'adresi', 
    'angani',
    'achari',
    'bwakia', 
    'bahari',
    'bahati',
    'baridi', 
    'bamvua', 
    'badamu', 
    'badani', 
    'badili', 
    'batili',
    'bakuli', 
    'beseni', 
    'bandia', 
    'badala', 
    'bakora',
    'bandua', 
    'banika',
    'barafu', 
    'baraji', 
    'baraza', 
    'barizi', 
    'barkoa', 
    'baruti', 
    'batiki', 
    'batiza', 
    'bayana', 
    'beberu', 
    'bazazi', 
    'bazoka', 
    'balozi', 
    'baluni', 
    'banana', 
    'baraka',
    'bamiza', 
    'bawaba', 
    'bazuka',
    'batana', 
    'bepari', 
    'bendua', 
    'besera', 
    'binamu', 
    'binuka', 
    'bingwa', 
    'biriji', 
    'bishoo', 
    'bizari', 
    'bitana', 
    'bobari', 
    'bokozi', 
    'bokoka', 
    'braili', 
    'brashi', 
    'buguja', 
    'buibui', 
    'bunguu', 
    'bupuru', 
    'buruji', 
    'busati', 
    'bwikia',
    'chafya',
    'chumvi',
    'chuchu', 
    'chafua', 
    'chagaa', 
    'chakaa', 
    'chagua', 
    'chakua', 
    'chambi', 
    'chamvi',
    'chamka', 
    'chamko', 
    'chambo', 
    'chanua', 
    'chanjo', 
    'chanja', 
    'chanzo', 
    'chapuo', 
    'chashi', 
    'chavua', 
    'chemba', 
    'chenza', 
    'chando', 
    'changa', 
    'changu', 
    'chanja', 
    'chanje', 
    'chapuo', 
    'chapwa', 
    'chapia', 
    'charua', 
    'chauka', 
    'chavua', 
    'cheche', 
    'chekeo', 
    'chenji', 
    'cheuwa', 
    'chicha', 
    'chimba', 
    'chinja', 
    'chipsi', 
    'chipua', 
    'chombo', 
    'chofuo', 
    'chimbo', 
    'chocho', 
    'chobea', 
    'chokoa', 
    'chogoe', 
    'chokaa', 
    'chokea', 
    'chonga', 
    'chomoa', 
    'chonge', 
    'chonda', 
    'chongo', 
    'chonza', 
    'chonjo', 
    'chovya', 
    'chovyo', 
    'chordo', 
    'chubwi', 
    'chubua', 
    'chujua',
    'chuguu', 
    'chukia', 
    'chukua',  
    'chumba', 
    'chunga', 
    'chungu', 
    'chupia', 
    'chuuza', 
    'chusha',
    'dadisa', 
    'dadisi', 
    'dafina', 
    'dabali', 
    'dachia', 
    'dakika', 
    'dandia', 
    'daraja', 
    'darasa', 
    'darizi', 
    'dalali',
    'dalili',
    'dachia', 
    'daamba', 
    'dafrau', 
    'dakawa', 
    'damara', 
    'damisi', 
    'daraba', 
    'darisi', 
    'durusu', 
    'dawala', 
    'dawati',
    'dandia', 
    'debeki', 
    'dedesa', 
    'dhambi', 
    'dhaifu', 
    'dharba', 
    'dhiraa',
    'diwani',
    'dibaji', 
    'dimbua', 
    'dikrii', 
    'dimbua', 
    'dimbwi', 
    'ditama', 
    'dizeli',
    'dosari', 
    'drafti', 
    'dukiza', 
    'dukizi', 
    'dumaza', 
    'dumuzi',
    'egesho', 
    'elekea', 
    'evusha',
    'halipo',
    'farasi', 
    'fahari',
    'fulani', 
    'fulana',
    'fasaha',
    'fasihi', 
    'falahi', 
    'fakiri', 
    'fanana', 
    'fanidi', 
    'fanusi', 
    'faraja', 
    'farisi', 
    'fariki', 
    'fasiki', 
    'fataki', 
    'fatika', 
    'fetehe', 
    'halipo', 
    'finyaa', 
    'funika',
    'filamu', 
    'fikira', 
    'fisidi', 
    'fitina', 
    'fomula', 
    'foliti', 
    'foloko', 
    'fukuta', 
    'fukuto', 
    'funama', 
    'fundua', 
    'furaha', 
    'furahi', 
    'furutu', 
    'futika', 
    'futuka', 
    'fuwele', 
    'fyanda',
    'fyatua', 
    'fyonya', 
    'fyonza', 
    'fungia',
    'gandua', 
    'gavana', 
    'gaguro', 
    'gahamu', 
    'ghafla', 
    'gwanda', 
    'gajeti', 
    'galimu', 
    'garasa', 
    'geukia', 
    'gegenu', 
    'ghaibu', 
    'ghushi', 
    'gidamu', 
    'girisi', 
    'gobore', 
    'gombea', 
    'goteza', 
    'gotama', 
    'gugumo', 
    'gungwi', 
    'gwanda',  
    'gwechu',  
    'gwenya',  
    'guberi', 
    'gubika', 
    'gubiko', 
    'guguma', 
    'gutuka',
    'halali', 
    'hatari',
    'haramu',
    'hatamu', 
    'halisi', 
    'hakika', 
    'hakiki', 
    'hariri',
    'hawara', 
    'hadimu', 
    'hamaki', 
    'hajati',
    'herufi', 
    'harufu',
    'hikima', 
    'hijabu', 
    'hiliki', 
    'hekima', 
    'hisani', 
    'huzuni', 
    'halaka', 
    'halasa', 
    'halafu', 
    'hazina', 
    'hafifu', 
    'halisi', 
    'halifa', 
    'halifu', 
    'haluli', 
    'hamasa', 
    'hapana', 
    'hanjam', 
    'harabu', 
    'harage', 
    'hanuni', 
    'haraja', 
    'haraka', 
    'harara', 
    'haribu', 
    'harija', 
    'hasada',  
    'hasara',  
    'harita', 
    'harubu', 
    'harufu', 
    'hasusa', 
    'hasibu', 
    'hesabu', 
    'hasidi', 
    'hatamu', 
    'hasimu', 
    'hatari', 
    'hasira', 
    'hasiri', 
    'hataza', 
    'hatibu', 
    'hatima', 
    'hawala', 
    'hatiri', 
    'hawili', 
    'hayati', 
    'hekalu', 
    'hazama', 
    'henezi', 
    'herini', 
    'hewala', 
    'hidaya', 
    'hekaya', 
    'hilaki', 
    'hirimu', 
    'himila', 
    'hirizi', 
    'himili', 
    'himiza', 
    'hitimu', 
    'hitari', 
    'hobesa', 
    'hodari', 
    'hohosa', 
    'hongea', 
    'holela', 
    'horowi', 
    'hoteli', 
    'hududi',
    'hudumu',
    'huduma', 
    'huenda', 
    'hakimu', 
    'hujaji', 
    'hujuma', 
    'hujumu', 
    'huluti', 
    'humusi', 
    'huntha', 
    'husudi', 
    'huruma',
    'ishara', 
    'idhini', 
    'ilhali', 
    'injini', 
    'inukia', 
    'ishiwa', 
    'israfu', 
    'itikia', 
    'injili',
    'jahazi', 
    'jaalia', 
    'janaba', 
    'jadili', 
    'jabari', 
    'jahimu', 
    'jahabu', 
    'jaketi', 
    'jalada', 
    'jahara', 
    'jeraha', 
    'jalali',  
    'jahili', 
    'jarida', 
    'jamali',  
    'jasiri',  
    'jawabu', 
    'jazana', 
    'jeleza', 
    'jidaba', 
    'jikimu', 
    'jukumu',
    'jinata', 
    'jirani',  
    'jokezi', 
    'junaha', 
    'jeneza', 
    'jiboda', 
    'malipo',
    'jihami', 
    'jihadi', 
    'jihini', 
    'jikita', 
    'jikaga', 
    'jikaza', 
    'jinaki', 
    'jokofu', 
    'juhudi',
    'kafara',
    'kanuni', 
    'kasoro', 
    'kukosa',
    'kijiko', 
    'kokoto', 
    'kiburi',
    'kibati', 
    'kigogo', 
    'kidogo', 
    'kiumbe', 
    'karamu', 
    'kalamu',
    'karani', 
    'kafiri', 
    'kusini', 
    'kiraka', 
    'kabuli', 
    'kafeni', 
    'kahati', 
    'kahini', 
    'kabili', 
    'kabati', 
    'kabati', 
    'kaanga', 
    'kababu', 
    'kabari', 
    'kijiti', 
    'karata', 
    'kakara', 
    'kutoka', 
    'katika', 
    'kuomba', 
    'kiungo',
    'lijamu',
    'mjanja', 
    'mawazo', 
    'masomo', 
    'mikasa', 
    'maisha', 
    'mnyama',
    'mawiyo', 
    'mgongo', 
    'maziwa', 
    'madini', 
    'mwanzo',  
    'mabavu', 
    'mapema', 
    'mpenzi', 
    'matuta', 
    'mlango', 
    'mpango', 
    'mkubwa', 
    'mchuzi', 
    'maneno', 
    'mshipa', 
    'mweupe',
    'mweusi', 
    'mpunga', 
    'msaada', 
    'makuti', 
    'muziki', 
    'mganga', 
    'mstari',
    'milele', 
    'mkondo', 
    'majani', 
    'mikono', 
    'nyingi',
    'nyinyi', 
    'nyanya', 
    'nyeupe', 
    'nyeusi', 
    'nafaka', 
    'nyumba', 
    'mgomba', 
    'nafasi',
    'orodha',
    'pamoja', 
    'pahali', 
    'patasi', 
    'polisi',
    'rushwa',
    'ruhusa',
    'sehemu', 
    'safura', 
    'saruji',
    'sitiri', 
    'sukari', 
    'sakafu', 
    'samaki', 
    'sanifu', 
    'suguru', 
    'sitini', 
    'sheria', 
    'shujaa',
    'tapeli', 
    'tengua',
    'upembe', 
    'ugomvi',
    'utomvu', 
    'ujumbe',
    'vyombo', 
    'viumbe', 
    'vipimo',
    'wadudu',
    'wakati', 
    'waraka', 
    'wageni', 
    'wakati',
    'zamani'
];

var guessList = [
    'viungo', 
    'wavuvi', 
    'dawiri', 
    'deheni', 
    'dirabu', 
    'tuhuma', 
    'komaza', 
    'diriki', 
    'kalidi', 
    'kalifu', 
    'kamani', 
    'kamari', 
    'kamasi', 
    'kamata', 
    'kamati', 
    'kambaa', 
    'kamera',
    'mizigo', 
    'kamusi', 
    'kanisa', 
    'kapani', 
    'kisawe', 
    'kapera', 
    'kisasi', 
    'kurusi', 
    'karama', 
    'koleza', 
    'karara', 
    'kokota', 
    'karibu', 
    'kitama', 
    'karati', 
    'karima', 
    'kitalu', 
    'karimu', 
    'kisutu', 
    'makali', 
    'kisomo', 
    'kariri', 
    'kasino', 
    'kasiki', 
    'kitapa', 
    'kasuku', 
    'kitani', 
    'kasoro', 
    'kisaga', 
    'katani', 
    'kiwiko', 
    'kataza', 
    'kiyuyu', 
    'katibu', 
    'kidole', 
    'kuruti', 
    'katili', 
    'kivazi', 
    'kaunda', 
    'kisogo', 
    'kitabu', 
    'kisima', 
    'kejeli', 
    'kivuno', 
    'kelele', 
    'kondoo', 
    'kiyama', 
    'kemeza', 
    'kiambo', 
    'kibaba', 
    'kunazi', 
    'kibaka', 
    'kokona',  
    'kibali', 
    'kiwera', 
    'kahaba', 
    'kiwavi', 
    'kibuyu', 
    'kiburi',
    'kibuja', 
    'kisimi',
    'kibutu', 
    'kidaka', 
    'kidako', 
    'kidevu', 
    'kidani',
    'kitufe', 
    'kidari',
    'kizibo',
    'kidato', 
    'kideri', 
    'kideme',
    'kizuka',
    'kidoko', 
    'kisiki',
    'kidoto',
    'kizazi',
    'kidusi', 
    'kifani', 
    'kienzo', 
    'kifafa', 
    'kuruta', 
    'kiduta',  
    'kigego', 
    'kitivo', 
    'kigaga', 
    'kigori', 
    'kigoda', 
    'kigusa', 
    'kigusa', 
    'kiguru', 
    'kijiji', 
    'kihodi', 
    'kizoro', 
    'kijusi', 
    'kilimi',
    'kikoti', 
    'kikope',
    'kwatua',
    'kikosi',
    'kimatu', 
    'kilimo', 
    'kipara', 
    'kipawa', 
    'kilifi', 
    'kipimo',
    'kipeuo',
    'kirihi',
    'kipigi',
    'kiporo',
    'kipigo',
    'kipimo',
    'kiraka',
    'kipuli',
    'kiriri',
    'kiroja',
    'kiriba',
    'koroga', 
    'mapepe',
    'korona',
    'kusuru',
    'kuwadi',
    'kwamua',
    'kwangu',
    'kwapua',
    'kwikwi',
    'laghai',
    'lahaja',
    'lakini',
    'labeka',
    'latifu', 
    'lakabu',
    'langua',
    'lawama',
    'legeza', 
    'lawiti',
    'likizo',
    'lazimu',
    'limbuo',
    'limbua',
    'luteni',
    'lufufu',
    'madaha',
    'makopa', 
    'madini', 
    'magube',
    'mafuta',
    'mahari',
    'mahaba',
    'makapi',
    'majuto',
    'makamu',
    'makala',
    'makini',
    'makeke', 
    'ukindu',
    'bidhaa', 
    'chamba', 
    'chapua', 
    'chocha', 
    'chuana', 
    'dazeni', 
    'dogori', 
    'dohani', 
    'egemea', 
    'fukaya', 
    'fukuka',
    'fuliza',
    'fulusi', 
    'fupiza', 
    'furika', 
    'futari', 
    'futuza',
    'fukiza', 
    'fyekua', 
    'fukuza', 
    'fatiha', 
    'fatuwa', 
    'hafifu',
    'himaya', 
    'homoni', 
    'huduma', 
    'huisha', 
    'ikweta', 
    'fisadi', 
    'foleni',
    'fitini', 
    'gazeti', 
    'gololi', 
    'giniza', 
    'gawadi', 
    'geleka',
    'guguna', 
    'gundua', 
    'gereji', 
    'ghasia', 
    'habari', 
    'harusi', 
    'hobela', 
    'jukumu', 
    'jumuia', 
    'jujumo', 
    'jarife', 
    'johari',
    'kuponi', 
    'jibari', 
    'jabali', 
    'kazana', 
    'kichwa', 
    'mshale', 
    'muziki', 
    'muhogo', 
    'mashua', 
    'tokeza', 
    'talaka', 
    'ijumaa',
    'ambayo',
    'sabuni',
    'habari',
    'salamu',
    'chepeo',
    'adhabu', 
    'afyuni', 
    'agulia', 
    'aidini', 
    'akania', 
    'akhiri', 
    'akrabu', 
    'adhimu', 
    'afandi', 
    'adisha',
    'ajwari', 
    'achana', 
    'adhana', 
    'afueni',
    'agizia',
    'aibika', 
    'akhera', 
    'albamu',
    'amilesi', 
    'anguka', 
    'anjari', 
    'askari', 
    'askofu', 
    'asmini', 
    'abiria', 
    'adresi', 
    'angani',
    'achari',
    'bwakia', 
    'bahari',
    'bahati',
    'baridi', 
    'bamvua', 
    'badamu', 
    'badani', 
    'badili', 
    'batili',
    'bakuli', 
    'beseni', 
    'bandia', 
    'badala', 
    'bakora',
    'bandua', 
    'banika',
    'barafu', 
    'baraji', 
    'baraza', 
    'barizi', 
    'barkoa', 
    'baruti', 
    'batiki', 
    'batiza', 
    'bayana', 
    'beberu', 
    'bazazi', 
    'bazoka', 
    'balozi', 
    'baluni', 
    'banana', 
    'baraka',
    'bamiza', 
    'bawaba', 
    'bazuka',
    'batana', 
    'bepari', 
    'bendua', 
    'besera', 
    'binamu', 
    'binuka', 
    'bingwa', 
    'biriji', 
    'bishoo', 
    'bizari', 
    'bitana', 
    'bobari', 
    'bokozi', 
    'bokoka', 
    'braili', 
    'brashi', 
    'buguja', 
    'buibui', 
    'bunguu', 
    'bupuru', 
    'buruji', 
    'busati', 
    'bwikia',
    'chafya',
    'chumvi',
    'chuchu', 
    'chafua', 
    'chagaa', 
    'chakaa', 
    'chagua', 
    'chakua', 
    'chambi', 
    'chamvi',
    'chamka', 
    'chamko', 
    'chambo', 
    'chanua', 
    'chanjo', 
    'chanja', 
    'chanzo', 
    'chapuo', 
    'chashi', 
    'chavua', 
    'chemba', 
    'chenza', 
    'chando', 
    'changa', 
    'changu', 
    'chanja', 
    'chanje', 
    'chapuo', 
    'chapwa', 
    'chapia', 
    'charua', 
    'chauka', 
    'chavua', 
    'cheche', 
    'chekeo', 
    'chenji', 
    'cheuwa', 
    'chicha', 
    'chimba', 
    'chinja', 
    'chipsi', 
    'chipua', 
    'chombo', 
    'chofuo', 
    'chimbo', 
    'chocho', 
    'chobea', 
    'chokoa', 
    'chogoe', 
    'chokaa', 
    'chokea', 
    'chonga', 
    'chomoa', 
    'chonge', 
    'chonda', 
    'chongo', 
    'chonza', 
    'chonjo', 
    'chovya', 
    'chovyo', 
    'chordo', 
    'chubwi', 
    'chubua', 
    'chujua',
    'chuguu', 
    'chukia', 
    'chukua',  
    'chumba', 
    'chunga', 
    'chungu', 
    'chupia', 
    'chuuza', 
    'chusha',
    'dadisa', 
    'dadisi', 
    'dafina', 
    'dabali', 
    'dachia', 
    'dakika', 
    'dandia', 
    'daraja',
    'daraka',
    'dangro',
    'kamili',
    'daraka',
    'wakala',
    'damisi',
    'hakuwa',
    'darasa', 
    'darizi', 
    'dalali',
    'dalili',
    'dachia', 
    'daamba', 
    'dafrau', 
    'dakawa', 
    'damara', 
    'damisi', 
    'daraba', 
    'darisi', 
    'durusu', 
    'dawala', 
    'dawati',
    'dandia', 
    'debeki', 
    'dedesa', 
    'dhambi', 
    'dhaifu', 
    'dharba', 
    'dhiraa',
    'diwani',
    'dibaji', 
    'dimbua', 
    'dikrii', 
    'dimbua', 
    'dimbwi', 
    'ditama', 
    'dizeli',
    'dosari', 
    'drafti', 
    'dukiza', 
    'dukizi', 
    'dumaza', 
    'dumuzi',
    'egesho', 
    'elekea', 
    'evusha',
    'halipo',
    'farasi', 
    'fahari',
    'fulani', 
    'fulana',
    'fasaha',
    'fasihi', 
    'falahi', 
    'fakiri', 
    'fanana', 
    'fanidi', 
    'fanusi', 
    'faraja', 
    'farisi', 
    'fariki', 
    'fasiki', 
    'fataki', 
    'fatika', 
    'fetehe', 
    'halipo', 
    'finyaa', 
    'funika',
    'filamu', 
    'fikira', 
    'fisidi', 
    'fitina', 
    'fomula', 
    'foliti', 
    'foloko', 
    'fukuta', 
    'fukuto', 
    'funama', 
    'fundua', 
    'furaha', 
    'furahi', 
    'furutu', 
    'futika', 
    'futuka', 
    'fuwele', 
    'fyanda',
    'fyatua', 
    'fyonya', 
    'fyonza', 
    'fungia',
    'gandua', 
    'gavana', 
    'gaguro', 
    'gahamu', 
    'ghafla', 
    'gwanda', 
    'gajeti', 
    'galimu', 
    'garasa', 
    'geukia', 
    'gegenu', 
    'ghaibu', 
    'ghushi', 
    'gidamu', 
    'girisi', 
    'gobore', 
    'gombea', 
    'goteza', 
    'gotama', 
    'gugumo', 
    'gungwi', 
    'gwanda',  
    'gwechu',  
    'gwenya',  
    'guberi', 
    'gubika', 
    'gubiko', 
    'guguma', 
    'gutuka',
    'jasusi',
    'sabini',
    'halali', 
    'hatari',
    'haramu',
    'hatamu', 
    'halisi', 
    'hakika', 
    'hakiki', 
    'hariri',
    'hawara', 
    'hadimu', 
    'hamaki', 
    'hajati',
    'herufi', 
    'harufu',
    'hikima', 
    'hijabu', 
    'hiliki', 
    'hekima', 
    'hisani', 
    'huzuni', 
    'halaka', 
    'halasa', 
    'halafu', 
    'hazina', 
    'hafifu', 
    'halisi', 
    'halifa', 
    'halifu', 
    'haluli', 
    'hamasa', 
    'hapana', 
    'hanjam', 
    'harabu', 
    'harage', 
    'hanuni', 
    'haraja', 
    'haraka', 
    'harara', 
    'haribu', 
    'harija', 
    'hasada',  
    'hasara',  
    'harita', 
    'harubu', 
    'harufu', 
    'hasusa', 
    'hasibu', 
    'hesabu', 
    'hasidi', 
    'hatamu', 
    'hasimu', 
    'hatari', 
    'hasira', 
    'hasiri', 
    'hataza', 
    'hatibu', 
    'hatima', 
    'hawala', 
    'hatiri', 
    'hawili', 
    'hayati', 
    'hekalu', 
    'hazama', 
    'henezi', 
    'herini', 
    'hewala', 
    'hidaya', 
    'hekaya', 
    'hilaki', 
    'hirimu', 
    'himila', 
    'hirizi', 
    'himili', 
    'himiza', 
    'hitimu', 
    'hitari', 
    'hobesa', 
    'hodari', 
    'hohosa', 
    'hongea', 
    'holela', 
    'horowi', 
    'hoteli', 
    'hududi',
    'hudumu',
    'huduma', 
    'huenda', 
    'hakimu', 
    'hujaji', 
    'hujuma', 
    'hujumu', 
    'huluti', 
    'humusi', 
    'huntha', 
    'husudi', 
    'huruma',
    'ishara', 
    'idhini', 
    'ilhali', 
    'injini', 
    'inukia', 
    'ishiwa', 
    'israfu', 
    'itikia', 
    'injili',
    'jahazi', 
    'jaalia', 
    'janaba', 
    'jadili', 
    'jabari', 
    'jahimu', 
    'jahabu', 
    'jaketi', 
    'jalada', 
    'jahara', 
    'jeraha', 
    'jalali',  
    'jahili', 
    'jarida', 
    'jamali',  
    'jasiri',  
    'jawabu', 
    'jazana', 
    'jeleza', 
    'jidaba', 
    'jikimu', 
    'jukumu',
    'jinata', 
    'jirani',  
    'jokezi', 
    'junaha', 
    'jeneza', 
    'jiboda', 
    'malipo',
    'jihami', 
    'jihadi', 
    'jihini', 
    'jikita', 
    'jikaga', 
    'jikaza', 
    'jinaki', 
    'jokofu', 
    'juhudi',
    'kafara',
    'kanuni', 
    'kasoro', 
    'kukosa',
    'kijiko', 
    'kokoto', 
    'kiburi',
    'kibati', 
    'kigogo', 
    'kidogo', 
    'kiumbe', 
    'karamu', 
    'kalamu',
    'karani', 
    'kafiri', 
    'kusini', 
    'kiraka', 
    'kabuli', 
    'kafeni', 
    'kahati', 
    'kahini', 
    'kabili', 
    'kabati', 
    'kabati', 
    'kaanga', 
    'kababu', 
    'kabari', 
    'kijiti', 
    'karata', 
    'kakara', 
    'kutoka', 
    'katika', 
    'kuomba', 
    'kiungo',
    'lijamu',
    'mjanja', 
    'mawazo', 
    'masomo', 
    'mikasa', 
    'maisha', 
    'mnyama',
    'mawiyo', 
    'mgongo', 
    'maziwa', 
    'madini', 
    'mwanzo', 
    'mabavu', 
    'mapema', 
    'mpenzi', 
    'matuta', 
    'mlango', 
    'mpango', 
    'mkubwa', 
    'mchuzi', 
    'maneno', 
    'mshipa', 
    'mweupe',
    'mweusi', 
    'mpunga', 
    'msaada', 
    'makuti', 
    'tumika',
    'dukani',
    'muziki', 
    'mganga', 
    'mstari',
    'milele', 
    'mkondo', 
    'majani', 
    'mikono', 
    'nyingi',
    'nyinyi', 
    'nyanya', 
    'nyeupe', 
    'nyeusi', 
    'nafaka', 
    'nyumba', 
    'mgomba', 
    'nafasi',
    'orodha',
    'pamoja', 
    'pahali', 
    'patasi', 
    'polisi',
    'rushwa',
    'ruhusa',
    'sehemu', 
    'safura', 
    'saruji',
    'sitiri', 
    'sukari', 
    'sakafu', 
    'samaki', 
    'sanifu', 
    'suguru', 
    'sitini', 
    'sheria', 
    'shujaa',
    'tapeli', 
    'tengua',
    'upembe', 
    'ugomvi',
    'utomvu', 
    'ujumbe',
    'vyombo', 
    'viumbe', 
    'vipimo',
    'wadudu',
    'wakati', 
    'waraka', 
    'wageni', 
    'wakati',
    'zamani'
];

guessList = guessList.concat(wordList);
var word = parseInt(Date.now() - new Date(2022, 0, 1)) / 1000 / 60 / 60 / 24 ;
word = wordList[Math.floor(word)].toUpperCase();

window.onload = function(){
    intialize();
}
      
function totalPlayed(){
    //total number of times played
    const totalPlayed = window.localStorage.getItem('totalPlayed') || 0;
    window.localStorage.setItem('totalPlayed', Number(totalPlayed)+1);
    document.getElementById("total-played").innerText = totalPlayed;
}

function totalWins(){
    //total wins
            const totalWins = window.localStorage.getItem('totalWins') || 0;
            window.localStorage.setItem('totalWins', Number(totalWins)+1);
            document.getElementById("total-wins").innerText = totalWins;
}

function currentStreak(){
    //current Streak
            const currentStreak = window.localStorage.getItem('currentStreak') || 0;
            window.localStorage.setItem('currentStreak', Number(currentStreak)+1);
            document.getElementById("current-streak").innerText = currentStreak;
}

function lost() {
    const currentStreak = window.localStorage.getItem('currentStreak') || 0;
     window.localStorage.setItem('currentStreak', 0);
     document.getElementById("current-streak").innerText = currentStreak;
}

function updateStatsModal() {
    const totalPlayed = window.localStorage.getItem('totalPlayed') || 0;
    const totalWins = window.localStorage.getItem('totalWins') || 0;
    const currentStreak = window.localStorage.getItem('currentStreak') || 0;
    
    document.getElementById("total-played").textContent = totalPlayed;
    document.getElementById("total-wins").textContent = totalWins;
    document.getElementById("current-streak").textContent = currentStreak;
}



function intialize() {

    // Create the game board
    for (let r = 0; r < height; r++) {
        for (let c = 0; c < width; c++) {
            // <span id="0-0" class="tile">P</span>
            let tile = document.createElement("span");
            tile.id = r.toString() + "-" + c.toString();
            tile.classList.add("tile");
            tile.innerText = "";
            document.getElementById("board").appendChild(tile);
        }
    }

    // Create the key board
    let keyboard = [
        ["Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P"],
        ["A", "S", "D", "F", "G", "H", "J", "K", "L", " "],
        ["Enter", "Z", "X", "C", "V", "B", "N", "M", "⌫" ]
    ]

    for (let i = 0; i < keyboard.length; i++) {
        let currRow = keyboard[i];
        let keyboardRow = document.createElement("div");
        keyboardRow.classList.add("keyboard-row");

        for (let j = 0; j < currRow.length; j++) {
            let keyTile = document.createElement("div");

            let key = currRow[j];
            keyTile.innerText = key;
            if (key == "Enter") {
                keyTile.id = "Enter";
            }
            else if (key == "⌫") {
                keyTile.id = "Backspace";
            }
            else if ("A" <= key && key <= "Z") {
                keyTile.id = "Key" + key; // "Key" + "A";
            } 

            keyTile.addEventListener("click", processKey);

            if (key == "Enter") {
                keyTile.classList.add("enter-key-tile");
            } else {
                keyTile.classList.add("key-tile");
            }
            keyboardRow.appendChild(keyTile);
        }
        document.body.appendChild(keyboardRow);
    }
    

    // Listen for Key Press
    document.addEventListener("keyup", (e) => {
        processInput(e);
    })

    
}



function processKey() {
    e = { "code" : this.id };
    processInput(e);
}

function processInput(e) {
    if (gameOver) return; 

    // alert(e.code);
    if ("KeyA" <= e.code && e.code <= "KeyZ") {
        if (col < width) {
            let currTile = document.getElementById(row.toString() + '-' + col.toString());
            if (currTile.innerText == "") {
                currTile.innerText = e.code[3];
                col += 1;
            }
        }
    }
    else if (e.code == "Backspace") {
        if (0 < col && col <= width) {
            col -=1;
        }
        let currTile = document.getElementById(row.toString() + '-' + col.toString());
        currTile.innerText = "";
    }

    else if (e.code == "Enter") {
        update();
    }

    if (!gameOver && row == height) {
        gameOver = true;
        document.getElementById("answer").innerText = "Samahani neno la leo ni "+word;
        totalPlayed();
        lost();
    }
}

function update() {
    let guess = "";
    document.getElementById("answer").innerText = "";

    //string up the guesses into the word
    for (let c = 0; c < width; c++) {
        let currTile = document.getElementById(row.toString() + '-' + c.toString());
        let letter = currTile.innerText;
        guess += letter;
    }

    guess = guess.toLowerCase(); //case sensitive
    console.log(guess);

    if (!guessList.includes(guess)) {
        document.getElementById("answer").innerText = "Neno hili halipo";
        return;
    } 
    //start processing guess
    let correct = 0;

    let letterCount = {}; //keep track of letter frequency, ex) KENNY -> {K:1, E:1, N:2, Y: 1}
    for (let i = 0; i < word.length; i++) {
        let letter = word[i];

        if (letterCount[letter]) {
           letterCount[letter] += 1;
        } 
        else {
           letterCount[letter] = 1;
        }
    }

    console.log(letterCount);

    //first iteration, check all the correct ones first
    for (let c = 0; c < width; c++) {
        let currTile = document.getElementById(row.toString() + '-' + c.toString());
        let letter = currTile.innerText;

        //Is it in the correct position?
        if (word[c] == letter) {
            currTile.classList.add("correct");

            let keyTile = document.getElementById("Key" + letter);
            keyTile.classList.remove("present");
            keyTile.classList.add("correct");

            correct += 1;
            letterCount[letter] -= 1; //deduct the letter count
        }

        if (correct == width) {
            document.getElementById("answer").innerText = "Hongera!Umepatia neno la leo";
            gameOver = true;
            totalPlayed();
            totalWins();
            currentStreak();
        }
        
    }

    console.log(letterCount);
    //go again and mark which ones are present but in wrong position
    for (let c = 0; c < width; c++) {
        let currTile = document.getElementById(row.toString() + '-' + c.toString());
        let letter = currTile.innerText;

        // skip the letter if it has been marked correct
        if (!currTile.classList.contains("correct")) {
            //Is it in the word?         //make sure we don't double count
            if (word.includes(letter) && letterCount[letter] > 0) {
                currTile.classList.add("present");
                
                let keyTile = document.getElementById("Key" + letter);
                if (!keyTile.classList.contains("correct")) {
                    keyTile.classList.add("present");
                }
                letterCount[letter] -= 1;
            } // Not in the word or (was in word but letters all used up to avoid overcount)
            else {
                currTile.classList.add("absent");
                let keyTile = document.getElementById("Key" + letter);
                keyTile.classList.add("absent")
            }
        }
    }

    row += 1; //start new row
    col = 0; //start at 0 for new row

    
}

